name: YAMLNPC
main: live.squi.yamlnpc.YAMLNPC
version: 1.1
api-version: 1.16
depend:
  - NPCLibPlugin
commands:
  npc:
    usage: /<command> (subcommand)
    description: YAMLNPC commands
    permission: yamlnpc.manage